### ISSUE TITLE
MapMyFitness Speed Data Missing

### ISSUE THREAD

**Issue by krisirk** [mlt/schwinn810#1]
It seems that when gpsbabel converts from the .points file into the .tcx file using babelize.sh that the speed or pace data doesn't work when imported into mapmyfitness.  I can give you an example of the files I've been trying to upload if you would like.

I'm using Ubuntu 11.10 with python3 and python3-serial installed and the data transfer from the device is flawless so far, so thank you for your excellent work.

**Comment by mlt** [comment]
Yeay! The first user! Thank you for testing!

There are lots of issues with how it is done for now but I believe it is just the beginning.
1. I don't know TCX standard whether it allows to store speed.
2. gpsbabel has limited support for sport related data. If you open [its source code](http://code.google.com/p/gpsbabel/source/browse/trunk/gpsbabel/gtrnctr.c?r=4148#347) you'll see, e.g.,  that it directly writes 0 calories into header.
3. Separate issue is how speed is reported along with track points. I tried to perform linear regression to find out coefficient for speed conversion by matching differences in distance with differences in time. It turned out it is slightly less than [160](https://github.com/mlt/schwinn810/blob/master/src/download.py#L176). I have no explanation what a weird transformation took place to get that multiplier.
4. In general I think speed is redundant in CSV export as it can be recalculated from differences in distance & time followed with some smoothing.
5. MapMyRun has API so in theory it is possible to update laps data, pace, etc after TCX has been imported

Also I'd appreciate if you can share your Prod.Id. and whatever is being reported by script. I'm not sure if you can edit wiki.

It is kind of awkward that there is no PM on github so you don't have to share where you ran with the world. I hope I've added you on MMF.

**Comment by mlt** [comment]
By the way, I don't know if you use udev, but I've noticed that it fails to extract data somewhere in the middle when the script is triggered by udev. Though it extracts just fine if ran standalone. I was thinking to add some sleep of a second before extraction. From other point of view just before it breaks it extracts complete batch of 0x24 bytes that just don't look like a point data. Have you experienced that issue?

**Comment by krisirk** [comment]
Upon looking at the .tcx files that the GPS NE Pro software outputs, it seems that there is a DistanceMeters tag at every trackpoint/waypoint.  My guess is that MapMyFitness/Run/Bike/Whatever is using the difference in distance vs time to calculate the speed or pace instead of calculating the distance based on the GPS coordinates.  Maybe it is as simple as getting that distance to be output into the .tcx file.

I haven't used udev to download from the watch, I've just run the python script manually.

I also found (and [posted on the woot forum](http://www.woot.com/forums/viewpost.aspx?PostID=4759056&PageIndex=4&ReplyCount=155#post4958337) for the watch) that the BridgeMin.dll file is a password protected Access database.  Try opening it with "danger" as the password to compare your data to the data pulled from the GPS NE Pro software.

**Comment by mlt** [comment]
Is there anything else that is badly missing in TCX format compared to supplied NEWCO software and in general?

Since gpsbabel does not write that data, there are 2 approaches
1. patch gpsbabel (would nicely follow unix philosophy)
2. write custom converter (would be anavoidable if we miss lots of stuff)

**Comment by krisirk** [comment]
I'm booting between Windows for the GPS NE Pro files and Ubuntu for your script to access the watch, so bear with me.

The Product ID from settings.py is M11153 01-020 E 11 12 04 00 25 30

I've created a Wiki page that I'll put the beginnings of the .tcx output from GPS NE Pro and from gpsbabel so that the xml tags can be seen.  Also, if you need to email me directly my address is <del>deleted</del>.

I've also uploaded two bike workouts and one run to MapMyFitness with the .tcx output from gpsbabel.  You should be able to see them since I've confirmed the friend request.

Kris

**Comment by krisirk** [comment]
I tried out your custom .tcx converter and it is just about there.  The heart rate and speed (or pace if the sport is running) now graph properly, as well as the elevation.  The only thing that is wrong is the splits for the laps.  Each Lap's < DistanceMeters > value should be the distance covered in that lap only, then the splits would work.

The calories at the beginning of each lap would also be for just that lap, though I don't think you'd even need them since MapMyFitness does a pretty good of estimating them.

< AverageHeartRateBMP > and < MaximumHeartRateBPM > as they appear in the lower set of code here:
https://github.com/mlt/schwinn810/wiki/Sample-.TCX-Files
could also be added at the beginning of each lap and would make the split data more accurate.  Right now it just shows the Max heart rate as whatever the first value is within that lap.

You can take a look at my run on the 18th, the one labeled "Test of .tcx files" is the one using the new csv converter and the other one is the gpsbabel converted one.

I'm amazed at how well this is coming along.  Thanks for all your hard work.

Kris

**Comment by mlt** [comment]
Thanks for testing! Once resultant XML passed schema validation, I gave up on further checking of details. Calories & distance should be correct now.

I've added lap's max heart rate. Regarding average one, I don't see it in data returned from device. I believe it should be there though. I might made a mistake by mislabeling MinHeart (in .laps) if it is an average heart rate in fact. But I think it is minimum. As an alternative, average heart rate can be calculated but it would require either to read .points twice or store it in memory.

Also could you actually post your prod.id as reported by watch itself (SET->PROD.ID)? I can't figure out what is what in that data. Something should be related to vendor, something to serial, and something to version I believe. I tried to mimic whatever is reported by GPS NE from NEWCO. But [its window caption has "0D"](https://github.com/mlt/schwinn810/wiki/Data-Format) in my case that I have no idea where comes from.

What would be really amazing is if there was a way to upload data back to watch. As I've mentioned I don't remember where, there is an option to Upload in GPS NE software. However I don't see any changes after "sending" data. From looking into communication transcription, it looks like that watch does not actually response at all on those write attempts :(

**Comment by krisirk** [comment]
The data in the .laps file labeled heart does seem to be the minimum HR for that lap.  However, the data in the .tracks file labeled heart seems to be the average HR for the entire track.  It would be nice to have the average HR for each lap (I'm kind of a data hound), but it isn't necessary.

The Product ID as reported in the watch is:
E111204
002530
1110162
01-020

Kris

**Comment by mlt** [comment]
I don't see Heart column in .laps . it [was  renamed](https://github.com/mlt/schwinn810/commit/6b37dfd7b7a04a016b2ca00763990edbebd3d56f#L0L126) awhile ago. Yes, for overall data, I don't add "Avg" prefix or something explicitly. "Heart" column for tracks and laps would imply average. So I believe lap average heart rate is probably still hiding in a combination of those "x" & "y" variables.

Thanks for prod.id. It looks like the 2nd line is a serial number as mine is 002882. And is the only number that is different. But I still don't know where is vendor ID and where is a firmware version or something in "M11153", "01-020", "E 11 12 04". Also it is a mystery what is 1110162. It is not reported in GPS NE.

If you want to be able to recover newly discovered variables from old exports, use --debug option. It will produce a binary dump /tmp/schwinn810.bin . You can rename and keep that file and use a path to it later in --port specification instead of /dev/ttyUSB0.

**Comment by krisirk** [comment]
I've been using the download.py dated April 14th, so I'm sure it's a bit behind.  I'll download the new one and try it on my next run or bike ride.  I'd try it sooner but I deleted all the tracks off my watch last time I downloaded with the GPS NE Pro software.

Kris

**Comment by mlt** [comment]
Good news. I've managed to figure out [what are x2-x6 variables are](https://github.com/mlt/schwinn810/wiki/Data-Format/_compare/784f0a5fe2f2bfb09ffc60a0e47aee77a60b44cc...b7336e2ce03f56db7b9763361b587ad377be40bb). I'll update download.py soon to get average heart rate for the lap.

I don't know how you "download" files from here but definitely git would allow you to update easily with just "git pull". You can "clone" this project with "git clone https://github.com/mlt/schwinn810.git"

**Comment by krisirk** [comment]
So it looks like cumulative heart beats is just saved as 3 bytes.  What if I have more than (2^24)-1 heart beats during my workout??  ;)  

I have actually been downloading the files individually by clicking on them then right clicking on the RAW box on the top right of the code to save.  I installed git and will use it from now on for keeping the files up to date.  I've never used git before so didn't even know I could do that.

Once again, thanks for all your hard work.

Kris

**Comment by mlt** [comment]
You are welcome! I kind of started it for myself but you provide invaluable feedback. I'd be lazy to check all the things.

Well... there are lots of limitations but it is not that easy to hit some. One prominent is that time stamp reported with points does not contain date:( So if you decide to run overnight, or stop timer and continue next day, your dates will be off. I don't know if it is the case with original software. But I just have no idea how it can be solved.

**Comment by krisirk** [comment]
I'm satisfied that this issue can be closed.  MMF is working great now.

Kris
